spring:
  application:
    name: Zero-Knowledge Vault Rebuild

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/Zero_Knowledge_Vault?serverTimezone=Asia/Seoul
    username: zkv
    password: ${MYSQL_PASSWORD}

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            scope: name, email, mobile
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response

app:
  jwt:
    issuer: zkv
    secret-key: ${JWT_SECRET_KEY}
    expired: 3600000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security.oauth2.client.endpoint: TRACE

domain:
  name: "http://localhost:8080"
